name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create directories
      working-directory: rotl
      run: mkdir obj bin
    - name: make
      working-directory: rotl
      run: make USE_CURSES=1
    - name: run tests
      working-directory: rotl
      run: bin/main
